Update README
Japan-DfinityInfoHub/generative-art-nft pull request #37
Opened 2022-05-28 01:19 UTC by bioerrorlog

# 概要・目的

Fixes #34

# 変更内容
## やったこと
- READMEの更新

## やらないこと

## 影響範囲
README

# 動作確認
https://github.com/Japan-DfinityInfoHub/generative-art-nft/tree/feature/update-readme

# 補足

2022-05-28 03:01 UTC, hoosan requested changes
README改修ありがとうございます！細かい点suggestions付けましたのでご確認ください🙏

2022-05-28 03:01 UTC, hoosan commented on README.md
> +You can get outputs as below, click the link to see the art images.
カンマの前後が別文ですのでセミコロンで繋ぐのが良いと思います🙏
```suggestion
You can get outputs as below; click the link to see the art images.
```

2022-05-28 03:01 UTC, hoosan commented on README.md
> +To generate generative art images and upload to the canister:
themを入れることでuploadの目的語が明確になります
```suggestion
To generate generative art images and upload them to the canister:
```

2022-05-28 03:01 UTC, hoosan commented on README.md
> +# Uplaod the images to the canister
Typoです🙏
```suggestion
# Upload the images to the canister
```

2022-05-28 11:40 UTC, hoosan commented on README.md
> +# Run cansiter e2e tests
typoです🙏
```suggestion
# Run canister e2e tests
```

2022-05-29 01:02 UTC, bioerrorlog commented
ありがとうございます！
Suggestion取り入れました.

2022-05-29 01:30 UTC, hoosan approved these changes
LGTMです！squashご了承ください🙏

2022-05-29 01:30 UTC, merged